### ISSUE TITLE
LocalDateTimeArgument doesn't persist correctly

### ISSUE THREAD

**Issue by kristoflemmens** [dropwizard/dropwizard-java8#1]
The code 
statement.setTimestamp(position, new Timestamp(value.toEpochSecond(ZoneOffset.UTC)));
should be
statement.setTimestamp(position, Timestamp.valueOf(value));

and in the mapper you can then use Timestamp#toLocalDateTime()

Now you insert the date incorrectly in the database. The database thinks you're in 1970 or something

**Comment by joschi** [comment]
Fixed by merging #2.
