### ISSUE TITLE
Add some docs on using JDBI

### ISSUE THREAD

**Issue by criccomini** [dropwizard/dropwizard-java8#14]
The README mentions Jackson and JSR when adding Java8Bundle. It looks like this doesn't actually do anything for JDBI though.

**Comment by criccomini** [comment]
Should mention:

1. Need to include dropwizard-java8-jdbi module.
2. Need to use io.dropwizard.java8.jdbi.DBIFactory rather than normal Dropwizard DBIFactory.
3. Need to annotate JDBI getter methods that return Optional<> with @SingleValueResult(Your.class).

**Comment by softarn** [comment]
https://github.com/dropwizard/dropwizard-java8/pull/16
