### ISSUE TITLE
Keeping dropwizard-java8 up to date

### ISSUE THREAD

**Issue by dconnelly** [dropwizard/dropwizard-java8#18]
Dropwizard-java8 is falling behind the main dropwizard project with regards to jackson dependencies. Wouldn't it be easier if this module were moved to an optional submodule of the main dropwizard project? I believe Maven can be configured so that the submodule could use a different target jdk from the main modules.

**Comment by joschi** [comment]
Did you find any incompatibilities you couldn't solve with dependency exclusions or with a proper `dependencyManagement` section in your Maven POM?

**Comment by dconnelly** [comment]
I was able to use a dependencyManagement section to align Jackson artifact versions and avoid any potential issues, but perhaps not everyone would think to try that. But I am still curious why this isn't part of the main dropwizard project which would make this a non-issue for everyone.

**Comment by nzroller** [comment]
We quite often use these java8 modules so it would be quite nice to have them released in tandem with dropwizard-core releases.

**Comment by joschi** [comment]
Preparations for Dropwizard 0.9.x have been done and Dropwizard 1.0.x won't need this module (since we plan to use Java 8 as baseline). Closing issue.
