### ISSUE TITLE
NoClassDefFoundError: hibernate's ValidatedValueUnwrapper

### ISSUE THREAD

**Issue by withoutairs** [dropwizard/dropwizard-java8#4]
Hi! I'm trying to use this bundle to get the [Jackson serializers for JSR-310 types](https://github.com/FasterXML/jackson-datatype-jsr310). If this is the wrong approach please let me know, I'm new to Dropwizard.

[Here is a commit](https://github.com/withoutairs/kaksidi/commit/f8a84718781b5d7a5ccd7d238a9a3dfd06559fc9) showing the changes I made to the application; its commit message has the full stacktrace but the root cause is a java.lang.NoClassDefFoundError: org/hibernate/validator/spi/valuehandling/ValidatedValueUnwrapper

Is there another bundle I need to add? I'm using Dropwizard 0.7.0.

Thanks!

**Comment by joschi** [comment]
The class in question has been introduced in Hibernate Validator 5.1.0.Final. Dropwizard 0.7.0 is using Hibernate Validator 5.0.2.Final.

Please upgrade to Dropwizard 0.7.1.
