### ISSUE TITLE
ResourceTestRule needs java8 providers to be registered

### ISSUE THREAD

**Issue by yunspace** [dropwizard/dropwizard-java8#5]
When running unit tests using `ResourceTestRule` none of the Java8 providers are registered by default, so weird behaviour would occur such as: `Optional.empty()` returning status 200 instead of 404

These scenarios are not failing in this project's unit tests because they are using `JerseyTest` with all providers registered instead of using `ResourceTestRule`. 

To work around I manually registered the providers when building `ResourceTestRule`

    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new DummyResource())
            .addProvider(OptionalMessageBodyWriter.class)
            .addProvider(OptionalParamFeature.class)
            .build();

Would it be worthwhile to note this in the README or create a brand new `Java8ResourceTestRule`?

**Comment by joschi** [comment]
I vote for putting it in the README file. I want to prevent having to (re-) create every class just to replace [`com.google.common.base.Optional<T>`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Optional.html) with [`java.util.Optional<T>`](http://docs.oracle.com/javase/8/docs/api/java/util/Optional.html).

**Comment by yunspace** [comment]
Ok, created PR #6
