### ISSUE TITLE
Dropwizard 0.8 support

### ISSUE THREAD

**Issue by cash1981** [dropwizard/dropwizard-java8#7]
In maven central there is only the 0.8.0-1 version, which I am guessing does not support Dropwizard 0.8
I see that the 0.8.0-3.SNAPSHOT does. When will you have a release which supports Dropwizard 0.8?

**Comment by joschi** [comment]
dropwizard-java8 0.8.0-1 supports Dropwizard 0.8.0.

**Comment by cash1981** [comment]
Yes sorry. It was some other maven issues unrelated to this repository.
