### ISSUE TITLE
ResourceTestRule throws: "Can not deserialize instance of java.time.LocalDate out of START_ARRAY token"

### ISSUE THREAD

**Issue by yunspace** [dropwizard/dropwizard-java8#8]
In 0.8.0 release, when using `ResourceTestRule` with all necessary `Providers` added:

    @ClassRule
    public static ResourceTestRule resources = ResourceTestRule.builder()
            .setMapper(MAPPER)
            .addResource(new DummyResource())
            .addProvider(OptionalMessageBodyWriter.class)
            .addProvider(OptionalParamFeature.class)
            .build();

and `ObjectMapper` that has all necessary `Modules` added:

    private static final ObjectMapper MAPPER = Jackson.newObjectMapper()
            .registerModules(new JavaOptionalModule())
            .registerModules(new JSR310Module());

It would throw the following error when serializing/deserializing `LocalDate` or `LocalDateTime`:

    Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.time.LocalDate out of START_ARRAY token
    at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@6d136eeb; line: 1, column: 2] (through reference chain: trunk.stream.model.Dummy["localDate"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835)

The Resource works correctly in Integration testing and behaves fine when running the application. I've created a standalone unit test that can reproduce this issue in this gist:

https://gist.github.com/yunspace/70947f5b889816425c85

It's really bizarre, when debugging through the code, the ObjectMapper used to read and write json definitely has all the correct `Modules` attached. But the result is different when running Integration vs Resource test.

**Comment by froden** [comment]
I had the same problem and it seems that the `ObjectMapper` instance is only registered on the server side of the `JerseyTest` and not on the client.

My workaround was to register a `JacksonJsonProvider` with the same mapper on the Jersey client:
```java
@BeforeClass
public static void initClient() {
    JacksonJsonProvider provider = new JacksonJaxbJsonProvider();
    provider.setMapper(MAPPER);
    resources.client().register(provider);
}
```

`ResourceTestRule` should probably override `configureClient` from `JerseyTest` and register the mapper like this:
```java
@Override
protected void configureClient(final ClientConfig config) {
    JacksonJsonProvider jsonProvider = new JacksonJaxbJsonProvider();
    jsonProvider.setMapper(mapper);
    config.register(jsonProvider);
}
```

I'll test this later and send a pull request if it works :)

**Comment by yunspace** [comment]
Thanks @froden this works. I will also test out your override approach.

**Comment by yunspace** [comment]
Resolved by https://github.com/dropwizard/dropwizard/pull/948, closing
